// Explicit integration check: real HTTP + MongoDB, isolated fixtures, no Messenger sends.
import "dotenv/config";
import mongoose from "mongoose";
import axios from "axios";
import assert from "node:assert/strict";
import Customer from "../src/models/Customer.js";
import Vehicle from "../src/models/Vehicle.js";
import MechanicSlot from "../src/models/MechanicSlot.js";
import Appointment from "../src/models/Appointment.js";

const ids = Object.fromEntries(["customer", "vehicle", "future", "past"].map(key => [key, new mongoose.Types.ObjectId()]));
const api = axios.create({ baseURL: `http://127.0.0.1:${process.env.PORT || 5000}`, timeout: 20000, validateStatus: () => true });
try {
  await mongoose.connect(process.env.MONGO_URI);
  // A reserved fictional number, never used to send any message.
  await Customer.create({ _id: ids.customer, name: "Automated booking verification", phone: "+12025550199" });
  await Vehicle.create({ _id: ids.vehicle, customerId: ids.customer, make: "Volkswagen", model: "Golf 7", year: 2018, engine: "1.4 TSI", mileage: 84500 });
  await MechanicSlot.create([
    { _id: ids.future, date: new Date(Date.now() + 7 * 86400000), startTime: "10:00", endTime: "11:00", mechanicName: "TEST ONLY" },
    { _id: ids.past, date: new Date(Date.now() - 86400000), startTime: "10:00", endTime: "11:00", mechanicName: "TEST ONLY" },
  ]);
  const payload = { customerId: String(ids.customer), vehicleId: String(ids.vehicle), slotId: String(ids.future), notes: "Automated integration verification; removed after test" };
  const past = await api.post("/api/tools/create-appointment", { ...payload, slotId: String(ids.past) });
  assert.equal(past.status, 409);
  const wrongOwner = await api.post("/api/tools/create-appointment", { ...payload, customerId: String(new mongoose.Types.ObjectId()) });
  assert.equal(wrongOwner.status, 400);
  const booked = await api.post("/api/tools/create-appointment", payload);
  assert.equal(booked.status, 201, JSON.stringify(booked.data));
  const retry = await api.post("/api/tools/create-appointment", payload);
  assert.equal(retry.status, 200);
  assert.equal(retry.data._id, booked.data._id);
  assert.equal(await Appointment.countDocuments({ customerId: ids.customer }), 1);
  assert.equal((await MechanicSlot.findById(ids.future)).isAvailable, false);
  console.log(JSON.stringify({ bookingVerified: true, appointmentId: booked.data._id, pastSlotRejected: true, invalidCustomerRejected: true, duplicatePrevented: true }));
} finally {
  // Delete only the exact fresh IDs generated by this run, never existing shop records.
  await Appointment.deleteMany({ customerId: ids.customer });
  await Vehicle.deleteOne({ _id: ids.vehicle });
  await Customer.deleteOne({ _id: ids.customer });
  await MechanicSlot.deleteMany({ _id: { $in: [ids.future, ids.past] } });
  await mongoose.disconnect();
}
