// Public information only; never render credentials or customer records.
const escape = value => String(value).replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char]));

export function privacyPage(env = process.env) {
  const operator = env.PRIVACY_OPERATOR_NAME?.trim();
  const email = env.PRIVACY_CONTACT_EMAIL?.trim();
  if (!operator || !/^[^\s<>@]+@[^\s<>@]+\.[^\s<>@]+$/.test(email || "")) return null;
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Privacy Policy | The Inbox Agent</title>
<style>body{font:17px/1.65 system-ui,sans-serif;color:#172337;background:#f5f7fb;margin:0}main{max-width:800px;margin:40px auto;padding:32px;background:white;border-radius:12px}h1,h2{line-height:1.25}a{color:#1459a6}footer{margin-top:32px;color:#526175}</style></head>
<body><!--email_off--><main><h1>Privacy Policy</h1><p>The Inbox Agent / My Hackathon Project</p><p>Last updated: 25 September 2026</p>
<h2>Who operates this service</h2><p>${escape(operator)} operates this customer-support messaging application. For privacy questions and requests, email <a href="mailto:${escape(email)}">${escape(email)}</a>.</p>
<h2>Information processed</h2><p>When you contact a connected Facebook Page or Instagram professional account, the app processes message text, platform-scoped sender and recipient identifiers, message identifiers and timestamps. It stores customer-support replies, conversation facts such as order numbers and return details you provide, classifications, staff notes, assignments and delivery status. Information you include in a message may contain personal data.</p>
<h2>Why the information is used</h2><p>The app uses this information to answer support questions, maintain conversation context, check inventory, apply support policies, route requests to staff, prevent duplicate replies and troubleshoot delivery. Aggregate inbox statistics measure support activity and processing time. The current project uses fictional order and payment examples; it does not execute payments or refunds.</p>
<h2>AI and service providers</h2><p>When AI is enabled, message text is sent to Groq's configured AI service to identify language and support intent. For conversational replies, the current message, up to three recent conversation turns, and the relevant policy-checked business response (which may include stock, prices or order status) are sent to the service to write and review a reply. The app removes known private fixture details and common email/phone patterns from this reply context, but this is not comprehensive anonymization. Business rules control decisions, and staff may review escalated conversations. Please do not send passwords, payment-card details or other unnecessary sensitive information. Meta processes messages on Facebook and Instagram. Cloudflare carries traffic through the public tunnel, and the operator's MongoDB database stores support records. These providers may process data in countries other than your own under their own terms and privacy policies.</p>
<p>Relevant provider policies: <a href="https://www.facebook.com/privacy/policy/">Meta</a>, <a href="https://groq.com/privacy-policy/">Groq</a>, and <a href="https://www.cloudflare.com/privacypolicy/">Cloudflare</a>.</p>
<h2>Storage and access</h2><p>Support records are stored in the operator's database and can be accessed through the staff inbox. The application does not currently apply an automatic deletion schedule to message records: they remain until the operator deletes them. Removing the app's access on Meta does not itself erase previously stored support records. Provider-held copies are subject to the provider's own retention practices.</p>
<h2 id="data-deletion">Privacy and data deletion requests</h2><p>Email <a href="mailto:${escape(email)}">${escape(email)}</a> with the subject "Privacy or data deletion request". Identify the Facebook Page or Instagram account you contacted, your account username and approximate conversation date. Do not send passwords. The operator may request information necessary to verify ownership before locating and manually deleting associated message events, support cases, conversation memory and staff replies. Requests about copies held by Meta or other providers may also need to be made to those providers.</p>
<p>You may also ask the operator about access to or correction of your information, or ask to stop automated assistance. Applicable privacy rights depend on your location and circumstances.</p>
<h2>Website and staff sessions</h2><p>This privacy page sets no application cookies. The separate staff dashboard uses a session cookie for authentication and stores staff account details and password hashes. Staff sessions expire after eight hours.</p>
<h2>Changes</h2><p>Updates to this policy will appear on this page with an updated date. Contact the operator above with questions.</p>
<footer>The Inbox Agent &middot; ${escape(operator)}</footer></main><!--/email_off--></body></html>`;
}
